#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: OGZkNjZkNTBmMjNlNWI4YzAwYTZkYTRkMGIxNmRhMzNmOWJmOTU0MjdhMDUxN2MxYmRiNmRiOWRmYmE1OTBlZWQ0NGNiMDAwMjllNWUyMDAyMWM2MmYzMDM3NmY1YjcyNjEwZA==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
